name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#jobs:
#  build:
#    runs-on: windows-latest
#
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Setup MSBuild.exe
#        uses: microsoft/setup-msbuild@v1.1
#
#      - name: Install .NET Core
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '7.0.x'
#      - name: Setup NuGet
#        uses: NuGet/setup-nuget@v1.0.5
#
#      - name: Restore NuGet packages
#        run: nuget restore XFiler.sln
#
#      - name: Build the Solution lab1
#        run: msbuild XFiler.sln  
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: labX
#          path: |
#            **/bin
            
jobs:
  build:
    
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: labX
          path: |
            **/bin