name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#jobs:
#  build:
#    runs-on: windows-latest
#
#
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Setup MSBuild.exe
#        uses: microsoft/setup-msbuild@v1.1
#
#      - name: Install .NET Core
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: '7.0.x'
#      - name: Setup NuGet
#        uses: NuGet/setup-nuget@v1.0.5
#
#      - name: Restore NuGet packages
#        run: nuget restore XFiler.sln
#
#      - name: Build the Solution lab1
#        run: msbuild XFiler.sln  
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: labX
#          path: |
#            **/bin
            
jobs:
  build:
    
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: 'Print manual run reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: .NET code metrics
        id: dotnet-code-metrics
        uses: dotnet/samples/github-actions/DotNet.GitHubAction@main
        env:
          GREETINGS: 'Hello, .NET developers!' # ${{ secrets.GITHUB_TOKEN }}
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          dir: ${{ './github-actions/DotNet.GitHubAction' }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        if: ${{ steps.dotnet-code-metrics.outputs.updated-metrics }} == 'true'
        with:
          title: '${{ steps.dotnet-code-metrics.outputs.summary-title }}'
          body: '${{ steps.dotnet-code-metrics.outputs.summary-details }}'
          commit-message: '.NET code metrics, automated pull request.'